TST1 = ctest
TST1_SRCS = ctest.c ra_tests.c pq_tests.c ht_tests.c

BUILDDIR = ../build
LIBS = ../build/libclxns.a

# Set RPATH on Mac OS
# LIBS = -Wl,-rpath,@executable_path/../build -lclxns

include ../lib/simplified-make/simplified.mk
